### ISSUE TITLE
Registered Folder does not show filesystem content to select folder

### ISSUE THREAD

**Issue by apphead** [repetier/Repetier-Server#105]
Win7x64, Repetier Server 0.90.4
Tested with Firefox 61.0.2  and Chrome 68.0.3440.106

![image](https://user-images.githubusercontent.com/505490/44273415-b817b180-a23f-11e8-8fdc-8e189ec2a8dd.png)

Clicking on Select Directory has no effect (as no folder is selected...)

**Comment by repetier** [comment]
Apperently a problem with windows. testing on Mac/Linux it works as supposed and under windows I get the same problem.. Will fix it for next update.
