### ISSUE TITLE
Build error with most current and updated raspbian in GCode.cpp.o

### ISSUE THREAD

**Issue by p1ngb4ck** [repetier/Repetier-Server#106]
As title says.

/opt/Repetier-Server/Repetier-Server/server/GCode.cpp:277:38: error: expected primary-expression before ‘>’ token
     return shared_ptr<GCodeDataPacket>(new GCodeDataPacket((int)st.length(),dp));
I suspect the most current libboost to be incompatible

**Comment by repetier** [comment]
This version is not supported any more. We provide a much improved version on http://www.repetier-server.com , please try that version. It comes already pre compiled.
