### ISSUE TITLE
Shutdown within server

### ISSUE THREAD

**Issue by smartroad** [repetier/Repetier-Server#25]
Hi (again)

I was wondering if it would be possible to have some sort of shutdown/reboot for the server within the web browser? Mainly for the RPi as it has now way of shutting down gracefully and just pulling out the power is a little dodgy (given I have just had to restore the SD card because doing that corrupted some system files).

Just a thought I had while using this, which I love BTW!

**Comment by fra87** [comment]
Was this feature implemented in repetier server?

**Comment by repetier** [comment]
Read in manual -> advanved setup. Works since 0.50 or so. Requires version from our homepage www.repetier-server.com
