### ISSUE TITLE
Directories for Model database

### ISSUE THREAD

**Issue by smartroad** [repetier/Repetier-Server#47]
Was just thinking that it would be really useful to have the model 'database' with some form of directory structure. I have a couple of things that are made from multiple parts and it would be nice to separate the designs from each other.

Just a thought :grinning:

**Comment by apphead** [comment]
I second that. The list gets really long after a while. Also, checkboxes to delete multiple models at once would be nice.

**Comment by repetier** [comment]
We now have groups in 0.75 that do exactly this.
