### ISSUE TITLE
Event g-code not run properly

### ISSUE THREAD

**Issue by kyrreaa** [repetier/Repetier-Server#75]
On some configurations the end job gcode or abort gcode is not performed properly.
Some commands may be run but not all.
Switch to relative mode and move up 50mm after job for example does not appear to work.

**Comment by repetier** [comment]
Yes, there are two bugs at least. On eis end gcode is not run I think (already fixed). The other is that a comment needs a space between command and ; or it will ignore the command.

**Comment by kyrreaa** [comment]
Perfect! A workaround atleast.

**Comment by repetier** [comment]
Yes, and we are working hard on 0.70 where these things are fixed :-)
