### ISSUE TITLE
User without user admin privledges can't find his api key!

### ISSUE THREAD

**Issue by kyrreaa** [repetier/Repetier-Server#77]
If you do not have user admin rights you cannot enter the screen showing your api key.
Is there any other page the user can find this or is this indeed a small bug?

**Comment by repetier** [comment]
Currently I consider this as design decision. Admin can decide if he lets him know the api key or not just like he lets him know the password. We will talk about it if we should allow users to see/modify their own settings.

**Comment by kyrreaa** [comment]
OK.  But the table with api keys is not copy/paste-able so it is hard to give someone their key.

**Comment by repetier** [comment]
Ok, I give it the class for copy paste. That at least should be possible.
