### ISSUE TITLE
Setting extruder and bed temperature

### ISSUE THREAD

**Issue by dragondgold** [repetier/Repetier-Server#83]
Hi! We are developing a new application for 3D printers and we decided to use Repetier Server for it. We need to set extruder and bed temperatures through the API and also if possible send GCode commands to the printer.

I can't see any way to achieve that using the Websockets API. Is this currently possible or I should get into the source code to implement it?

Thank you!

**Comment by repetier** [comment]
According to 
http://www.repetier-server.com/manuals/programming/API/index.html

the command you need is send with parameter cmd containing a single gcode.

**Comment by dragondgold** [comment]
Thank you! I missed that
