### ISSUE TITLE
"Lights on / off" button missing!?

### ISSUE THREAD

**Issue by KissmanCZ** [repetier/Repetier-Server#91]
Hello! Where I can found "lights on / off" button which I see on some screenshot in version 60?

![b845bf1e-3085-11e5-9f10-0d2d5956476b](https://cloud.githubusercontent.com/assets/13331823/17459424/3fefd02a-5c37-11e6-9d27-227a22af1679.png)

**Comment by repetier** [comment]
Not sure where we lost it, but I can also not find the button. Will add it for 0.80.
