### ISSUE TITLE
Wifi access does not work on unsecure networks

### ISSUE THREAD

**Issue by innovo3d** [repetier/Repetier-Server#96]
I'm not fully familiar with network systems, but twice this last week I have visited Universities which have an unsecure (no password) Wifi networks for guests and students.  I connected my printer to the Wifi network successfully, or so it seems because it gave me an ip address that looked something like 10.10.1.193, however I could not connect my phone or computer to the Repetier Server Web Interface using the IP address given.

I'm posting here because I do not understand if it's an issue within the network configuration (firewall, access, etc...) or the Repetier Server.  Is there any work around so that we can enable Wifi Access to the printer?  The access point (AP) is still not working properly (at least not for my android phone) so that's not yet an alternative option.

If anyone can please help clarify that would really help.

**Comment by repetier** [comment]
10.x is a private network. You can only login there if you are also logged in into the same wifi network.

There is always also th epossibility that port 3344 is blocked in a network, but if they are so careless to let anyone in I not really suspect that.
