### ISSUE TITLE
Rasp Pi Repetier Server Communication issue

### ISSUE THREAD

**Issue by seacuello** [repetier/Repetier-Server#97]
Hi - 

Im having some trouble connecting to my 3D printer via repetier-server running on a raspberry pi 3

I ran the cmake command with the debugging on, but do not know where to look for its output tp try and find out why i cannot connect when entering the ip address with port :3344

Any help is geeatly appreciated to a newb like myself!  Thanks!

-Stephen

**Comment by repetier** [comment]
Please use our official builds from www.repetier-server.com - this is an old outdated version.
